// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VokabelTrainer.Api.Data;

#nullable disable

namespace VokabelTrainer.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260321220621_AddHintToVocabulary")]
    partial class AddHintToVocabulary
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("VokabelTrainer.Api.Data.Entities.BoxEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Box")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessionsUntilReview")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VocabularyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VocabularyId");

                    b.HasIndex("UserId", "VocabularyId")
                        .IsUnique();

                    b.ToTable("BoxEntries");
                });

            modelBuilder.Entity("VokabelTrainer.Api.Data.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlagSvg")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("VokabelTrainer.Api.Data.Entities.TrainingAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AnsweredAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GivenAnswer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ResponseSeconds")
                        .HasColumnType("REAL");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VocabularyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("VocabularyId");

                    b.ToTable("TrainingAnswers");
                });

            modelBuilder.Entity("VokabelTrainer.Api.Data.Entities.TrainingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CorrectAnswers")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ListId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxVocabulary")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ListId");

                    b.HasIndex("UserId");

                    b.ToTable("TrainingSessions");
                });

            modelBuilder.Entity("VokabelTrainer.Api.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInitialized")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VokabelTrainer.Api.Data.Entities.Vocabulary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hint")
                        .HasColumnType("TEXT");

                    b.Property<int>("ListId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Translations")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ListId");

                    b.ToTable("Vocabularies");
                });

            modelBuilder.Entity("VokabelTrainer.Api.Data.Entities.VocabularyList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceLanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetLanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SourceLanguageId");

                    b.HasIndex("TargetLanguageId");

                    b.HasIndex("UserId");

                    b.ToTable("VocabularyLists");
                });

            modelBuilder.Entity("VokabelTrainer.Api.Data.Entities.BoxEntry", b =>
                {
                    b.HasOne("VokabelTrainer.Api.Data.Entities.User", "User")
                        .WithMany("BoxEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VokabelTrainer.Api.Data.Entities.Vocabulary", "Vocabulary")
                        .WithMany("BoxEntries")
                        .HasForeignKey("VocabularyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Vocabulary");
                });

            modelBuilder.Entity("VokabelTrainer.Api.Data.Entities.TrainingAnswer", b =>
                {
                    b.HasOne("VokabelTrainer.Api.Data.Entities.TrainingSession", "Session")
                        .WithMany("Answers")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VokabelTrainer.Api.Data.Entities.Vocabulary", "Vocabulary")
                        .WithMany("TrainingAnswers")
                        .HasForeignKey("VocabularyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("Vocabulary");
                });

            modelBuilder.Entity("VokabelTrainer.Api.Data.Entities.TrainingSession", b =>
                {
                    b.HasOne("VokabelTrainer.Api.Data.Entities.VocabularyList", "List")
                        .WithMany()
                        .HasForeignKey("ListId");

                    b.HasOne("VokabelTrainer.Api.Data.Entities.User", "User")
                        .WithMany("TrainingSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("List");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VokabelTrainer.Api.Data.Entities.Vocabulary", b =>
                {
                    b.HasOne("VokabelTrainer.Api.Data.Entities.VocabularyList", "List")
                        .WithMany("Vocabularies")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("List");
                });

            modelBuilder.Entity("VokabelTrainer.Api.Data.Entities.VocabularyList", b =>
                {
                    b.HasOne("VokabelTrainer.Api.Data.Entities.Language", "SourceLanguage")
                        .WithMany()
                        .HasForeignKey("SourceLanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VokabelTrainer.Api.Data.Entities.Language", "TargetLanguage")
                        .WithMany()
                        .HasForeignKey("TargetLanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VokabelTrainer.Api.Data.Entities.User", "User")
                        .WithMany("VocabularyLists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceLanguage");

                    b.Navigation("TargetLanguage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VokabelTrainer.Api.Data.Entities.TrainingSession", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("VokabelTrainer.Api.Data.Entities.User", b =>
                {
                    b.Navigation("BoxEntries");

                    b.Navigation("TrainingSessions");

                    b.Navigation("VocabularyLists");
                });

            modelBuilder.Entity("VokabelTrainer.Api.Data.Entities.Vocabulary", b =>
                {
                    b.Navigation("BoxEntries");

                    b.Navigation("TrainingAnswers");
                });

            modelBuilder.Entity("VokabelTrainer.Api.Data.Entities.VocabularyList", b =>
                {
                    b.Navigation("Vocabularies");
                });
#pragma warning restore 612, 618
        }
    }
}
